### PR TITLE
Update pytest-variables to version 2.0.0

### PR DESCRIPTION
**Pull request by rxm7706**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
@birdsarah @davehunt
This is ready to review. Updates to support version 2.0,

**Comment by nicoddemus** [comment]
@davehunt can you also add me as maintainer here? Thanks!

**Comment by rxm7706** [comment]
> @davehunt can you also add me as maintainer here? Thanks!

@nicoddemus I've added you to the maintainers list.

**Review by nicoddemus — APPROVED** [review]

**Comment by nicoddemus** [comment]
Thanks, unfortunately that will only have an effect when it lands on `master`.

@davehunt and @birdsarah, I have reviewed and everything looks good, please go ahead and merge it when you have the chance. :+1:

**Pull request merged**
